# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsumoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('deal', models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)'), ('select', 'AppSumo Select (28/10/21 -)')], max_length=8, null=True)),
                ('redeemed', models.DateTimeField(null=True)),
                ('refunded_before', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AppsumoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rows', models.BigIntegerField()),
                ('reason', models.TextField()),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AppsumoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review_link', models.CharField(error_messages={'unique': "A user has linked to this review for their team. If you think this is a mistake, reach out to support and we'll sort it out for you."}, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Paste the exact link as displayed on AppSumo', regex='^https:\\/\\/appsumo\\.com\\/products\\/marketplace-gyana\\/\\#r[0-9]{6,9}$')])),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchasedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='cypress/purchased_codes')),
                ('deal', models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)'), ('select', 'AppSumo Select (28/10/21 -)')], max_length=8)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RefundedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='cypress/refunded_codes')),
                ('downloaded', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UploadedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='cypress/uploaded_codes')),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
