# Generated by Django 3.2.5 on 2021-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsumocode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
