# Generated by Django 3.2.5 on 2021-08-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsumo', '0002_alter_appsumocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsumocode',
            name='redeemed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
