# Generated by Django 3.2.5 on 2021-08-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0003_appsumocode_redeemed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='')),
                ('downloaded', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='')),
                ('downloaded', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
