# Generated by Django 3.2.7 on 2021-11-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_auto_20211119_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='is_scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
