# Generated by Django 3.2.7 on 2021-12-07 01:01

from django.db import migrations


def forwards_func(apps, schema_editor):

    Sheet = apps.get_model("sheets", "Sheet")

    for sheet in Sheet.objects.all():
        sheet.succeeded_at = sheet.drive_file_last_modified_at_sync

        # this is an estimate for backwards compatability
        if sheet.integration.state == "error":
            sheet.failed_at = sheet.sync_started

        sheet.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0014_remove_sheet_next_daily_sync"),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop)
    ]
