# Generated by Django 3.2.7 on 2021-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_remove_sheet_next_daily_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_name',
            field=models.CharField(blank=True, help_text='Select a specific sheet by submitting the tab name', max_length=50, null=True, verbose_name='Sheet selection'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='cell_range',
            field=models.CharField(blank=True, help_text='Select a range of cells e.g. A2:D14', max_length=64, null=True),
        ),
    ]
