# Generated by Django 3.2.11 on 2022-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='icon',
            field=models.CharField(default='fa-flask', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flag',
            name='is_public_beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='title',
            field=models.CharField(default='Beta Feature', max_length=128),
            preserve_default=False,
        ),
    ]
