airtable:
  icon_path: airtable.svg
  id: airtable
  name: Airtable
amplitude:
  icon_path: amplitude.svg
  id: amplitude
  name: Amplitude
apache_kafka:
  icon_path: apache_kafka.svg
  id: apache_kafka
  name: Apache Kafka
apple_search_ads:
  icon_path: apple_search_ads.svg
  id: apple_search_ads
  name: Apple Search Ads
asana:
  icon_path: asana.svg
  id: asana
  name: Asana
aurora:
  icon_path: aurora.png
  id: aurora
  name: Aurora MySQL
azure_sql_db:
  icon_path: azure_sql_db.png
  id: azure_sql_db
  name: Azure SQL Database
bingads:
  icon_path: bingads.svg
  id: bingads
  name: Microsoft Advertising
box:
  icon_path: box.svg
  id: box
  name: Box
documentdb:
  icon_path: documentdb.svg
  id: documentdb
  name: Amazon DocumentDB
dropbox:
  icon_path: dropbox.svg
  id: dropbox
  name: Dropbox
dynamics_365:
  icon_path: dynamics_365.svg
  id: dynamics_365
  name: Microsoft Dynamics 365
dynamodb:
  icon_path: dynamodb.svg
  id: dynamodb
  name: DynamoDB
email:
  icon_path: email.svg
  id: email
  name: Email
facebook:
  icon_path: facebook.svg
  id: facebook
  name: Facebook Ad Insights
facebook_pages:
  icon_path: facebook_pages.svg
  id: facebook_pages
  name: Facebook Pages
freshdesk:
  icon_path: freshdesk.svg
  id: freshdesk
  name: Freshdesk
front:
  icon_path: front.svg
  id: front
  name: Front
ftp:
  icon_path: ftp.svg
  id: ftp
  name: FTP
gcs:
  icon_path: gcs.svg
  id: gcs
  name: Google Cloud Storage
github:
  icon_path: github.svg
  id: github
  name: GitHub
google_ads:
  icon_path: adwords.png
  id: google_ads
  name: Google Ads
google_analytics:
  icon_path: google_analytics.svg
  id: google_analytics
  name: Google Analytics
google_analytics_4:
  icon_path: google_analytics_4.svg
  id: google_analytics_4
  name: Google Analytics 4
google_drive:
  icon_path: google_drive.svg
  id: google_drive
  name: Google Drive
google_play:
  icon_path: google_play.svg
  id: google_play
  name: Google Play
google_search_console:
  icon_path: google_search_console.svg
  id: google_search_console
  name: Google Search Console
google_sheets:
  icon_path: google_sheets.svg
  id: google_sheets
  name: Google Sheets
greenhouse:
  icon_path: greenhouse.svg
  id: greenhouse
  name: Greenhouse
heap:
  icon_path: heap.svg
  id: heap
  name: Heap
height:
  icon_path: height.svg
  id: height
  name: Height
helpscout:
  icon_path: helpscout.svg
  id: helpscout
  name: Help Scout
hubspot:
  icon_path: hubspot.svg
  id: hubspot
  name: Hubspot
instagram_business:
  icon_path: instagram_business.png
  id: instagram_business
  name: Instagram Business
intercom:
  icon_path: intercom.svg
  id: intercom
  name: Intercom
itunes_connect:
  icon_path: itunes_connect.png
  id: itunes_connect
  name: Apple App Store
jira:
  icon_path: jira.svg
  id: jira
  name: Jira
klaviyo:
  icon_path: klaviyo.svg
  id: klaviyo
  name: Klaviyo
kustomer:
  icon_path: kustomer.svg
  id: kustomer
  name: Kustomer
lever:
  icon_path: lever.svg
  id: lever
  name: Lever
linkedin_ads:
  icon_path: linkedin_ads.svg
  id: linkedin_ads
  name: LinkedIn Ad Analytics
linkedin_company_pages:
  icon_path: linkedin_company_pages.svg
  id: linkedin_company_pages
  name: LinkedIn Company Pages
magento_mysql:
  icon_path: magento_mysql.png
  id: magento_mysql
  name: Magento MySQL
mailchimp:
  icon_path: mailchimp.svg
  id: mailchimp
  name: Mailchimp
mandrill:
  icon_path: mandrill.svg
  id: mandrill
  name: Mandrill
maria:
  icon_path: maria.png
  id: maria
  name: MariaDB
microsoft_lists:
  icon_path: microsoft_lists.svg
  id: microsoft_lists
  name: Microsoft Lists
mixpanel:
  icon_path: mixpanel.svg
  id: mixpanel
  name: Mixpanel
mongo:
  icon_path: mongo.svg
  id: mongo
  name: MongoDB
mysql:
  icon_path: mysql.png
  id: mysql
  name: MySQL
one_drive:
  icon_path: one_drive.svg
  id: one_drive
  name: OneDrive
oracle:
  icon_path: oracle.svg
  id: oracle
  name: Oracle
pinterest_ads:
  icon_path: pinterest_ads.svg
  id: pinterest_ads
  name: Pinterest Ads
pipedrive:
  icon_path: pipedrive.svg
  id: pipedrive
  name: Pipedrive
postgres:
  icon_path: postgres.svg
  id: postgres
  name: PostgreSQL
quickbooks:
  icon_path: quickbooks.svg
  id: quickbooks
  name: QuickBooks
recharge:
  icon_path: recharge.svg
  id: recharge
  name: ReCharge
recurly:
  icon_path: recurly.svg
  id: recurly
  name: Recurly
s3:
  icon_path: s3.svg
  id: s3
  name: Amazon S3
sage_intacct:
  icon_path: sage_intacct.svg
  id: sage_intacct
  name: Sage Intacct
salesforce:
  icon_path: salesforce.svg
  id: salesforce
  name: Salesforce
segment:
  icon_path: segment.svg
  id: segment
  name: Segment
sendgrid:
  icon_path: sendgrid.svg
  id: sendgrid
  name: SendGrid
sftp:
  icon_path: sftp.svg
  id: sftp
  name: SFTP
share_point:
  icon_path: share_point.svg
  id: share_point
  name: SharePoint
shopify:
  icon_path: shopify.svg
  id: shopify
  name: Shopify
snapchat_ads:
  icon_path: snapchat_ads.png
  id: snapchat_ads
  name: Snapchat Ads
snowplow:
  icon_path: snowplow.svg
  id: snowplow
  name: Snowplow
sql_server:
  icon_path: sql_server.svg
  id: sql_server
  name: SQL Server
square:
  icon_path: square.png
  id: square
  name: Square
stripe:
  icon_path: stripe.svg
  id: stripe
  name: Stripe
survey_monkey:
  icon_path: survey_monkey.svg
  id: survey_monkey
  name: SurveyMonkey
taboola:
  icon_path: taboola.svg
  id: taboola
  name: Taboola
tiktok_ads:
  icon_path: tiktok_ads.svg
  id: tiktok_ads
  name: Tiktok Ads
twilio:
  icon_path: twilio.svg
  id: twilio
  name: Twilio
twitter:
  icon_path: twitter.svg
  id: twitter
  name: Twitter Organic
twitter_ads:
  icon_path: twitter_ads.svg
  id: twitter_ads
  name: Twitter Ads
typeform:
  icon_path: typeform.svg
  id: typeform
  name: Typeform
webhooks:
  icon_path: webhooks.svg
  id: webhooks
  name: Webhooks
xero:
  icon_path: xero.svg
  id: xero
  name: Xero
youtube_analytics:
  icon_path: youtube_analytics.svg
  id: youtube_analytics
  name: YouTube Analytics
zendesk:
  icon_path: zendesk.svg
  id: zendesk
  name: Zendesk Support
zoho_crm:
  icon_path: zoho_crm.svg
  id: zoho_crm
  name: Zoho CRM
zuora:
  icon_path: zuora.svg
  id: zuora
  name: Zuora
