# Generated by Django 3.2.5 on 2021-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_node_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sentiment_column',
            field=models.CharField(blank=True, help_text='Select the text column to get the sentiment of.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Get data'), ('output', 'Save data'), ('select', 'Select columns'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add'), ('rename', 'Rename'), ('text', 'Text'), ('formula', 'Formula'), ('distinct', 'Distinct'), ('pivot', 'Pivot'), ('unpivot', 'Unpivot'), ('intersect', 'Intersection'), ('window', 'Window'), ('sentiment', 'Sentiment')], max_length=16),
        ),
    ]
