# Generated by Django 3.2.6 on 2021-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_auto_20210823_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='always_use_credits',
            field=models.BooleanField(default=False),
        ),
    ]
