# Generated by Django 3.2.6 on 2021-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_node_always_use_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='credit_use_confirmed',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='uses_credits',
            field=models.IntegerField(default=0),
        ),
    ]
