# Generated by Django 3.2.7 on 2021-11-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0014_node_has_been_saved"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="NodeParents",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "from_node",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="parent",
                                to="nodes.node",
                            ),
                        ),
                        (
                            "to_node",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="child",
                                to="nodes.node",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="node",
                    name="parents",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="children",
                        through="nodes.NodeParents",
                        to="nodes.Node",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE nodes_node_parents RENAME TO nodes_nodeparents",
                    reverse_sql="ALTER TABLE nodes_nodeparents RENAME TO nodes_node_parents",
                )
            ],
        )
    ]
