# Generated by Django 3.2.7 on 2021-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0015_auto_20211117_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeparents',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
