# Generated by Django 3.2.7 on 2021-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_nodeparents_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeparents',
            old_name='from_node',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='nodeparents',
            old_name='to_node',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(blank=True, through='nodes.NodeParents', to='nodes.Node'),
        ),
    ]
