# Generated by Django 3.2.7 on 2021-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0012_auto_20211213_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationcolumn',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aggregationcolumn',
            name='rounding',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='rounding',
            field=models.IntegerField(default=2),
        ),
    ]
