# Generated by Django 3.2.11 on 2022-02-02 10:38

import apps.base.clone
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0022_alter_node_input_table'),
        ('columns', '0014_column_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('how', models.CharField(choices=[('inner', 'Inner'), ('outer', 'Outer'), ('left', 'Left'), ('right', 'Right')], default='inner', help_text='Select the join method, more information in the docs', max_length=12)),
                ('left_column', models.CharField(help_text='Choose the left join column', max_length=300)),
                ('right_column', models.CharField(help_text='Choose the right join column', max_length=300)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_columns', to='nodes.node')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, apps.base.clone.CloneMixin, models.Model),
        ),
    ]
