# Generated by Django 3.2.11 on 2022-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0015_joincolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincolumn',
            name='left_index',
            field=models.IntegerField(default=0),
        ),
    ]
