# Generated by Django 3.2.11 on 2022-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0019_auto_20220221_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortcolumn',
            name='sort_index',
            field=models.TextField(default='0'),
        ),
    ]
