# Generated by Django 3.2.11 on 2022-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0020_historicaladdcolumn_historicalaggregationcolumn_historicalcolumn_historicalconvertcolumn_historicale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladdcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical add column', 'verbose_name_plural': 'historical add columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalaggregationcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aggregation column', 'verbose_name_plural': 'historical aggregation columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical column', 'verbose_name_plural': 'historical columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalconvertcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical convert column', 'verbose_name_plural': 'historical convert columns'},
        ),
        migrations.AlterModelOptions(
            name='historicaleditcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical edit column', 'verbose_name_plural': 'historical edit columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalformulacolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical formula column', 'verbose_name_plural': 'historical formula columns'},
        ),
        migrations.AlterModelOptions(
            name='historicaljoincolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical join column', 'verbose_name_plural': 'historical join columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalrenamecolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical rename column', 'verbose_name_plural': 'historical rename columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalsecondarycolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical secondary column', 'verbose_name_plural': 'historical secondary columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalsortcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sort column', 'verbose_name_plural': 'historical sort columns'},
        ),
        migrations.AlterModelOptions(
            name='historicalwindowcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical window column', 'verbose_name_plural': 'historical window columns'},
        ),
        migrations.AlterField(
            model_name='historicaladdcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaggregationcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalconvertcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleditcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalformulacolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaljoincolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrenamecolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsecondarycolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsortcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwindowcolumn',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
