# Generated by Django 3.2.12 on 2022-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0022_auto_20220503_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcolumn',
            options={'ordering': ('-sort_index',)},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('-sort_index',)},
        ),
        migrations.AddField(
            model_name='aggregationcolumn',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='column',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalaggregationcolumn',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
    ]
