# Generated by Django 3.2.7 on 2021-12-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='daily_schedule_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='periodic_task',
        ),
    ]
