# Generated by Django 3.2.7 on 2021-12-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20211206_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='daily_schedule_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='periodic_task',
        ),
    ]
