# Generated by Django 3.2 on 2021-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widget_visual_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='visual_kind',
        ),
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('table', 'Table'), ('column2d', 'Column'), ('line', 'Line'), ('pie2d', 'Pie')], max_length=32),
        ),
    ]
