# Generated by Django 3.2.7 on 2021-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0036_alter_widget_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='dateslice_column',
            field=models.CharField(help_text='Select a temporal column that will be used when using the dashboard date slicer', max_length=300, null=True),
        ),
    ]
