# Generated by Django 3.2.7 on 2021-12-10 11:09

import apps.widgets.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0039_widget_date_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='widget',
            name='palette_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='#5D62B5', max_length=7), default=apps.widgets.models.getFusionThemePalette, size=10),
        ),
    ]
