# Generated by Django 3.2.7 on 2021-12-10 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0040_auto_20211210_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='background_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='palette_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='#5D62B5', max_length=7), null=True, size=10),
        ),
    ]
