# Generated by Django 3.2.7 on 2021-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0041_auto_20211210_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='show_tooltips',
            field=models.BooleanField(null=True),
        ),
    ]
