# Generated by Django 3.2.7 on 2021-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0042_auto_20211213_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='font_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
