# Generated by Django 3.2.7 on 2021-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0042_widget_show_tooltips'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='font_size',
            field=models.IntegerField(null=True),
        ),
    ]
