# Generated by Django 3.2.11 on 2022-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0054_historicalcombinationchart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcombinationchart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical combination chart', 'verbose_name_plural': 'historical combination charts'},
        ),
        migrations.AlterModelOptions(
            name='historicalwidget',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical widget', 'verbose_name_plural': 'historical widgets'},
        ),
        migrations.AlterField(
            model_name='historicalcombinationchart',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwidget',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
