[tool.djlint]
blank_line_after_tag = "load,extends"
custom_blocks = "timezone,flag"
ignore = "T003,H021,H006,H013,H016"
indent = 2
max_line_length = 100
profile = "django"
use_gitignore = true

[tool.black]
extend-exclude = '''
(
  /(
    apps/cookiecutter-app
    | .+/migrate
    | .+/migrations
  )/
)
'''

[tool.isort]
extend_skip = ['migrations', 'migrate', 'apps/cookiecutter-app']
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "gyana.settings.development"

[tool.coverage.run]
branch = true
omit = ["*/migrations/*", "apps/cookiecutter-app/*"]
plugins = ["django_coverage_plugin"]
source = ["apps"]
