# Generated by Django 3.2.7 on 2021-12-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0024_alter_integration_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('json_path', models.TextField(default='$')),
                ('ndjson_file', models.FileField(null=True, upload_to='cypress/custom_api_jsonnl')),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
