# Generated by Django 3.2.11 on 2022-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0025_historicalfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfilter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical filter', 'verbose_name_plural': 'historical filters'},
        ),
        migrations.AlterField(
            model_name='historicalfilter',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
