# Generated by Django 3.2.6 on 2021-08-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_alter_integration_state'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.integration')),
                ('template_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.templateinstance')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
