# Generated by Django 3.2.7 on 2021-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateSlicer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "date_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("today", "Today"),
                            ("yesterday", "Yesterday"),
                            ("thisweek", "This week (starts Monday)"),
                            ("lastweek", "Last week (starts Monday)"),
                            ("last7", "Last 7 days"),
                            ("last14", "Last 14 days"),
                            ("last28", "Last 28 days"),
                            ("thismonth", "This month to date"),
                            ("lastmonth", "Last month"),
                            ("last30", "Last 30 days"),
                            ("last90", "Last 90 days"),
                            ("thisquarter", "This quarter to date"),
                            ("lastquarter", "Last quarter"),
                            ("last180", "Last 180 days"),
                            ("last12month", "Last 12 months"),
                            ("lastyear", "Last calendar year"),
                            ("thisyear", "This year (January - today)"),
                            ("custom", "Custom"),
                        ],
                        default="thisyear",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated",),
                "abstract": False,
            },
        ),
    ]
