# Generated by Django 3.2.7 on 2021-12-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0020_alter_integration_options'),
        ('workflows', '0045_auto_20211203_2239'),
        ('django_celery_results', '0010_remove_duplicate_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task_id', models.UUIDField()),
                ('source', models.CharField(choices=[('integration', 'Integration'), ('workflow', 'Workflow')], max_length=16)),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
