# Generated by Django 3.2.7 on 2021-12-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0006_auto_20211217_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='oauth2_authorization_base_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='oauth2_client_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='oauth2_client_secret',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='oauth2_state',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='oauth2_token',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='oauth2_token_url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
