# Generated by Django 3.2.7 on 2021-11-05 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_auto_20211105_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='palette_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), null=True, size=20),
        ),
    ]
