# Generated by Django 3.2.7 on 2021-11-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dateslicers', '0001_initial'),
        ('dashboards', '0015_alter_dashboard_palette_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date_slicer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dateslicers.dateslicer'),
        ),
    ]
