# Generated by Django 3.2.7 on 2021-11-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dateslicers", "0001_initial"),
        ("dashboards", "0016_alter_dashboard_shared_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="date_slicer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dateslicers.dateslicer",
            ),
        ),
    ]
