# Generated by Django 3.2.7 on 2021-12-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='font_size',
            field=models.IntegerField(default='16'),
        ),
    ]
