# Generated by Django 3.2.7 on 2021-11-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dateslicers", "0002_dateslicer_date_range"),
        ("dashboards", "0017_dashboard_date_slicer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="date_slicer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dateslicers.dateslicer",
            ),
        ),
    ]
