# Generated by Django 3.2.7 on 2021-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_auto_20211214_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
