# Generated by Django 3.2.7 on 2021-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_dashboard_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='font_family',
            field=models.CharField(choices=[('Roboto', 'Roboto')], default='Roboto', max_length=30),
        ),
    ]
