# Generated by Django 3.2.11 on 2022-03-08 15:44

import apps.base.clone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_historicaldashboard_historicalpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldashboard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dashboard', 'verbose_name_plural': 'historical dashboards'},
        ),
        migrations.AlterModelOptions(
            name='historicalpage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical page', 'verbose_name_plural': 'historical pages'},
        ),
        migrations.AlterField(
            model_name='historicaldashboard',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='DashboardVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
