# Generated by Django 3.2.11 on 2022-03-07 12:47

import django.db.models.deletion
from django.db import migrations, models

import apps.base.clone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0024_historicaldashboard_historicalpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "historical_dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version",
                        to="dashboards.historicaldashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated",),
                "abstract": False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
