# Generated by Django 3.2.12 on 2022-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0027_auto_populatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardversion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
