# Generated by Django 3.2.7 on 2021-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('table_created', 'Table created'), ('exported', 'Exported'), ('succeeded', 'Succeeded')], default='running', max_length=16),
        ),
    ]
