# Generated by Django 3.2.7 on 2021-11-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0014_node_has_been_saved'),
        ('tables', '0015_alter_table_source'),
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
        migrations.AlterField(
            model_name='export',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('table_created', 'Table created'), ('exported', 'Exported')], default='running', max_length=16),
        ),
    ]
