# Generated by Django 3.2.7 on 2021-11-09 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_export_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='gcs_path',
        ),
        migrations.RemoveField(
            model_name='export',
            name='status',
        ),
        migrations.AddField(
            model_name='export',
            name='exported_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='gcs_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
