# Generated by Django 3.2.7 on 2021-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20210928_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='source',
            field=models.CharField(choices=[('integration', 'Integration'), ('workflow_node', 'Workflow node'), ('intermediate_node', 'Intermediate node'), ('cache_node', 'Cache node'), ('export', 'Export')], max_length=18),
        ),
    ]
