# Generated by Django 3.2.12 on 2022-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220505_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_allowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
