# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='integration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration'),
        ),
    ]
