# Generated by Django 3.2.6 on 2021-09-07 13:28

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0004_auto_20210811_2255"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="fivetran_succeeded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=utc),
            ),
            preserve_default=False,
        ),
    ]
