# Generated by Django 3.2.7 on 2021-11-15 21:54
import datetime

import pytz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0012_auto_20211105_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="next_daily_sync",
            field=models.DateTimeField(
                default=datetime.datetime(1970, 1, 1, 0, 0).astimezone(pytz.UTC)
            ),
            preserve_default=False,
        ),
    ]
