# Generated by Django 3.2.7 on 2021-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0014_connector_is_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='is_scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
