# Generated by Django 3.2.11 on 2022-01-27 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0015_remove_connector_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='prebuilt_reports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AddField(
            model_name='connector',
            name='timeframe_months',
            field=models.CharField(choices=[('THREE', '3'), ('SIX', '6'), ('TWELVE', '12'), ('TWENTY_FOUR', '24'), ('ALL_TIME', 'All time')], default='THREE', max_length=16),
        ),
    ]
