# Generated by Django 3.2.5 on 2021-08-06 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="integrations.integration",
                    ),
                ),
                ("file", models.TextField()),
                ("external_table_sync_task_id", models.UUIDField(null=True)),
                ("has_initial_sync", models.BooleanField(default=False)),
                ("last_synced", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            """
        INSERT INTO uploads_upload
            (integration_id, file, external_table_sync_task_id, has_initial_sync, last_synced, created, updated)
        SELECT id, file, external_table_sync_task_id, has_initial_sync, last_synced, created, updated
        FROM integrations_integration
        where kind = 'csv'
        ;
        """
        ),
    ]
