# Generated by Django 4.0.8 on 2024-04-01 15:23

import apps.uploads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integration_kind'),
        ('uploads', '0002_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=apps.uploads.models.upload_to),
        ),
        migrations.AlterField(
            model_name='upload',
            name='integration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integration'),
        ),
    ]
