# Generated by Django 4.0.8 on 2024-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_gcs_path',
            field=models.TextField(null=True),
        ),
    ]
