# Generated by Django 3.2.11 on 2022-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnIndexPage',
        ),
    ]
