# Generated by Django 3.2.11 on 2022-02-01 20:31

import apps.learn.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_learnpage_stream_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnpage',
            name='stream_body',
        ),
        migrations.AlterField(
            model_name='learnpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('loom', apps.learn.models.LoomBlock())]),
        ),
    ]
