# Generated by Django 3.2.11 on 2022-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_historicalcontrol_historicalcontrolwidget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontrol',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical control', 'verbose_name_plural': 'historical controls'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontrolwidget',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical control widget', 'verbose_name_plural': 'historical control widgets'},
        ),
        migrations.AlterField(
            model_name='historicalcontrol',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrolwidget',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
