# Generated by Django 3.2 on 2021-05-05 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflows', '0009_auto_20210505_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='select_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('select', 'Select'), ('join', 'Join')], max_length=16),
        ),
    ]
