adroll:
  service_type: reporting_api
  static_config:
    table: adroll_table
adwords:
  static_config:
    sync_mode: AllAccounts
    timeframe_months: ALL_TIME
    # reports:
    #   - table: account_stats
    #     config_type: Prebuilt
    #     prebuilt_report: ACCOUNT_STATS
    #   - table: account_hourly_stats
    #     config_type: Prebuilt
    #     prebuilt_report: ACCOUNT_HOURLY_STATS
    #   - table: ad_stats
    #     config_type: Prebuilt
    #     prebuilt_report: AD_STATS
    #   - table: ad_group_stats
    #     config_type: Prebuilt
    #     prebuilt_report: AD_GROUP_STATS
    #   - table: ad_group_hourly_stats
    #     config_type: Prebuilt
    #     prebuilt_report: AD_GROUP_HOURLY_STATS
    #   - table: audience_stats
    #     config_type: Prebuilt
    #     prebuilt_report: AUDIENCE_STATS
    #   - table: campaign_stats
    #     config_type: Prebuilt
    #     prebuilt_report: CAMPAIGN_STATS
    #   - table: campaign_hourly_stats
    #     config_type: Prebuilt
    #     prebuilt_report: CAMPAIGN_HOURLY_STATS
    #   - table: keyword_stats
    #     config_type: Prebuilt
    #     prebuilt_report: KEYWORD_STATS
amplitude: {}
apple_search_ads: {}
asana: {}
aurora:
  service_type: database
aurora_postgres:
  service_type: database
azure_postgres:
  service_type: database
azure_sql_db:
  service_type: database
bingads: {}
braintree: {}
branch: {}
delighted: {}
dynamodb: {}
facebook_ad_account:
  sunset: true
facebook_ads:
  static_config:
    timeframe_months: SIX
facebook_pages: {}
freshdesk: {}
front: {}
github: {}
google_analytics:
  static_config:
    sync_mode: AllAccounts
    timeframe_months: SIX
    reports:
      - table: adwords_campaigns
        config_type: Prebuilt
        prebuilt_report: ADWORDS_CAMPAIGNS
      - table: adwords_hourly_stats
        config_type: Prebuilt
        prebuilt_report: ADWORDS_HOURLY_STATS
      - table: adwords_keyword
        config_type: Prebuilt
        prebuilt_report: ADWORDS_KEYWORD
      - table: audience_overview
        config_type: Prebuilt
        prebuilt_report: AUDIENCE_OVERVIEW
      - table: browser_and_operating_system_overview
        config_type: Prebuilt
        prebuilt_report: BROWSER_AND_OPERATING_SYSTEM_OVERVIEW
      - table: campaign_performance
        config_type: Prebuilt
        prebuilt_report: CAMPAIGN_PERFORMANCE
      - table: channel_traffic
        config_type: Prebuilt
        prebuilt_report: CHANNEL_TRAFFIC
      - table: events_overview
        config_type: Prebuilt
        prebuilt_report: EVENTS_OVERVIEW
      - table: social_media_acquisitions
        config_type: Prebuilt
        prebuilt_report: SOCIAL_MEDIA_ACQUISITIONS
      - table: traffic
        config_type: Prebuilt
        prebuilt_report: TRAFFIC
google_cloud_postgresql:
  service_type: database
google_cloud_mysql:
  service_type: database
google_search_console: {}
google_sheets:
  internal: true
  service_type: reporting_api
  static_config:
    table: sheets_table
greenhouse: {}
heap: {}
height: {}
helpscout: {}
heroku_postgres:
  service_type: database
hubspot: {}
instagram_business: {}
intercom: {}
jira: {}
linkedin_company_pages: {}
klaviyo: {}
kustomer: {}
lever: {}
linkedin_ads: {}
magento_mysql:
  service_type: database
magento_mysql_rds:
  service_type: database
mailchimp: {}
mandrill: {}
maria:
  service_type: database
maria_rds:
  service_type: database
maria_azure:
  service_type: database
mixpanel: {}
mongo:
  service_type: database
mysql:
  service_type: database
mysql_azure:
  service_type: database
mysql_rds:
  service_type: database
outbrain: {}
pardot: {}
pinterest_ads: {}
pipedrive: {}
postgres:
  service_type: database
postgres_rds:
  service_type: database
quickbooks: {}
recharge: {}
recurly: {}
sage_intacct: {}
salesforce: {}
segment:
  service_type: event_tracking
sendgrid: {}
shopify: {}
snapchat_ads: {}
snowplow:
  service_type: event_tracking
sql_server:
  service_type: database
sql_server_rds:
  service_type: database
square: {}
stripe: {}
survey_monkey: {}
taboola: {}
tiktok_ads: {}
twilio: {}
twitter: {}
typeform: {}
webhooks:
  service_type: webhooks
  static_config:
    table: webhooks_table
uservoice: {}
xero: {}
youtube_analytics:
  service_type: reporting_api
  static_config:
    table: youtube_analytics_table
zendesk: {}
zendesk_chat: {}
zendesk_sunshine: {}
