# Generated by Django 3.2.7 on 2021-12-07 01:05

from django.db import migrations


def failed(workflow):
    return any(node.error is not None for node in workflow.nodes.all())


def forwards_func(apps, schema_editor):

    Workflow = apps.get_model("workflows", "Workflow")

    for workflow in Workflow.objects.all():
        if failed(workflow):
            workflow.failed_at = workflow.last_run
        else:
            workflow.succeeded_at = workflow.last_run

        workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0045_auto_20211203_2239"),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop)
    ]
