# Generated by Django 3.2.7 on 2021-12-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0047_auto_20211209_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='last_run',
        ),
    ]
