# Generated by Django 3.2.5 on 2021-08-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_remove_team_enabled'),
    ]

    operations = [
    ]
