# Generated by Django 3.2.12 on 2022-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_team_has_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='override_rows_per_integration_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
