# Generated by Django 3.2.7 on 2021-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_run_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='succeeded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
