name: Django CI

on:
  push:
    branches: [ main, feature/github-actions ]
  pull_request:
    branches: [ main, feature/github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: '***'
          POSTGRES_DB: 'gyana'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
        
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - uses: HatsuneMiku3939/direnv-action@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # - uses: abatilo/actions-poetry@v2.0.0
    #   with:
    #     poetry-version: 1.1.5
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    # - name: Install Python Dependencies
    #   run: poetry install
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Node Dependencies
      run: yarn
    - name: Build assets
      run: yarn build
    - name: Run migrations
      run: just migrate
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: |
          just dev
          just celery
        wait-on: 'http://localhost:8000'