name: Pytest Unit Tests

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: '***'
          POSTGRES_DB: 'gyana'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
        # required for collectstatic
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: gyana-1511894275181
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Install Node Dependencies
        run: npm install
      - name: Build assets
        run: npm run build:dev
      - name: Collect static
        run: just collectstatic
      - name: Pytest run
        run: just test-e2e
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
