name: Pytest Unit Tests

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - uses: HatsuneMiku3939/direnv-action@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List
      run: ls
    - name: Pytest run
      run: just test